"""Add created_at to Service

Revision ID: 960db9625e7d
Revises: 7be5842bbc4a
Create Date: 2025-07-30 10:12:50.811346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960db9625e7d'
down_revision = '7be5842bbc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
